name: Terraform

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  
  terraform-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID}}:role/github-actions-prod-role
          aws-region: us-east-1

      - name: Verify AWS Identity (OIDC)
        run: aws sts get-caller-identity

      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Format
        run: terraform fmt -check -recursive
        working-directory: terraform/

      - name: Terraform Validate
        run: terraform init -backend=false && terraform validate
        working-directory: terraform/

      - uses: actions/checkout@v4
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/
          framework: terraform
          soft_fail: false # The pipeline will stop if security gaps are found
          # check: CKV_AWS_111,CKV_AWS_135 # Example: specific security checks // It's commented so it scans everyting by default